# Generated by Django 5.0.1 on 2024-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Half'), ('F', 'Full')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CF', 'Coffee'), ('SNK', 'Snacks'), ('SD', 'Soft Drinks'), ('SHK', 'Shakes')], max_length=3),
        ),
    ]
